"""依赖锁一致性门禁（scripts/check_requirements_lock.py）的单测：
用 tmp 文件驱动名字级校验逻辑，不触碰仓库真实清单。"""

import importlib.util
import sys
from pathlib import Path

SCRIPT = Path(__file__).resolve().parent.parent / "scripts" / "check_requirements_lock.py"
spec = importlib.util.spec_from_file_location("check_requirements_lock", SCRIPT)
mod = importlib.util.module_from_spec(spec)
sys.modules["check_requirements_lock"] = mod
spec.loader.exec_module(mod)


def test_direct_deps_strips_comments_markers_and_extras():
    text = "\n".join(
        [
            "# 注释行",
            "",
            "requests",
            "opencv-python>=4.8",
            "PyYAML; sys_platform == 'win32'",
            "mysql-connector-python[ssl]==8.2",
            "  # 行尾注释",
        ]
    )
    assert mod.direct_deps(text) == {"requests", "opencv-python", "pyyaml", "mysql-connector-python"}


def test_pep503_normalization_folds_separators():
    assert mod.norm("Python_Dotenv") == "python-dotenv"
    assert mod.norm("mysql-connector-python") == "mysql-connector-python"


def test_locked_names_only_counts_pin_lines():
    text = "\n".join(
        [
            "# This file was autogenerated by uv via the following command:",
            "#    uv pip compile requirements.txt -o requirements.lock.txt --universal --header --strip-extras",
            "aiohttp==3.14.3",
            "    # via -r requirements.txt",
            "numpy==2.5.3",
            "some-pkg==1.0 ; python_version >= '3.11'",
        ]
    )
    assert mod.locked_names(text) == {"aiohttp", "numpy", "some-pkg"}


def test_main_exits_nonzero_when_lock_missing(tmp_path, monkeypatch, capsys):
    monkeypatch.setattr(mod, "MANIFEST", tmp_path / "requirements.txt")
    monkeypatch.setattr(mod, "LOCK", tmp_path / "requirements.lock.txt")
    (tmp_path / "requirements.txt").write_text("requests\n", encoding="utf-8")
    assert mod.main() == 1
    assert "缺少" in capsys.readouterr().out


def test_main_reports_missing_coverage(tmp_path, monkeypatch, capsys):
    monkeypatch.setattr(mod, "MANIFEST", tmp_path / "requirements.txt")
    monkeypatch.setattr(mod, "LOCK", tmp_path / "requirements.lock.txt")
    (tmp_path / "requirements.txt").write_text("requests\nnewpkg\n", encoding="utf-8")
    (tmp_path / "requirements.lock.txt").write_text("requests==2.32.3\n", encoding="utf-8")
    assert mod.main() == 1
    out = capsys.readouterr().out
    assert "newpkg" in out and "重新生成" in out


def test_main_passes_when_covered(tmp_path, monkeypatch, capsys):
    monkeypatch.setattr(mod, "MANIFEST", tmp_path / "requirements.txt")
    monkeypatch.setattr(mod, "LOCK", tmp_path / "requirements.lock.txt")
    (tmp_path / "requirements.txt").write_text("requests\nSQLAlchemy_Alchemy\n", encoding="utf-8")
    (tmp_path / "requirements.lock.txt").write_text("requests==2.32.3\nsqlalchemy-alchemy==2.0\n", encoding="utf-8")
    assert mod.main() == 0
    assert "一致" in capsys.readouterr().out
